// Source-of-truth English UI strings. Every other language file in this
// directory is a Gemini-generated translation of exactly this object,
// generated by scripts/generate-translations.mjs — keep keys in sync.
const en = {
  app: {
    name: "Sahakar Sathi",
    tagline: "Cooperative guidance, in your language.",
    description:
      "Instant answers on cooperative law, Ministry of Cooperation schemes, PACS services, PMFBY crop insurance and grievance redressal — by text or voice.",
    org: "Ministry of Cooperation · National Council for Cooperative Training",
  },

  login: {
    welcomeBack: "Welcome back",
    signInSubtitle: "Sign in to continue to your assistant.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    signIn: "Sign in",
    noAccountYet: "Contact your PACS or cooperative officer for account access.",
  },

  common: {
    loading: "Loading…",
    save: "Save",
    saveChanges: "Save changes",
    saved: "Saved.",
    cancel: "Cancel",
    submit: "Submit",
    new: "New",
    settings: "Settings",
    signOut: "Sign out",
    back: "Back",
    language: "Language",
    optional: "Optional",
  },

  dashboard: {
    namaste: "Namaste",
    subtitle: "Ask about cooperative law, schemes, PACS services or crop insurance — in any language.",
    composerPlaceholder: "Ask anything about cooperatives…",
    listening: "Listening…",
    transcribing: "Transcribing…",
    thinking: "Thinking…",
    disclaimer: "Guidance only — not a substitute for official legal advice.",
    voiceInput: "Voice input",
    muteReplies: "Mute voice replies",
    unmuteReplies: "Unmute voice replies",
    schemesHeading: "Schemes",
    fileGrievance: "File a grievance",
    suggestionLawTitle: "Cooperative law",
    suggestionLawQuestion: "What are the rights of a member in a cooperative society?",
    suggestionPmfbyTitle: "PMFBY",
    suggestionPmfbyQuestion: "How do I claim crop insurance under PMFBY?",
    suggestionPacsTitle: "PACS services",
    suggestionPacsQuestion: "What services can I get at my nearest PACS?",
    suggestionFinanceTitle: "Financial literacy",
    suggestionFinanceQuestion: "How does a Kisan Credit Card work?",
    explainScheme: "Explain the {name} scheme — benefits and eligibility.",
    fileGrievancePrompt: "I want to file a grievance about my cooperative society.",
    connectionError: "I could not reach the assistant service. Check your connection and try again.",
    voiceUnsupported: "Voice input is not supported in this browser. Try Chrome.",
  },

  grievances: {
    title: "Grievances",
    yourGrievances: "Your grievances",
    subtitle: "Track issues raised about your cooperative society or PACS.",
    fileNew: "File a grievance",
    formHint: "Describe the issue clearly. A ticket number is generated automatically.",
    category: "Category",
    categoryGeneral: "General grievance",
    categoryLaw: "Cooperative law / by-laws",
    categoryPacs: "PACS service issue",
    categoryScheme: "Ministry scheme",
    categoryPmfby: "PMFBY / crop insurance",
    categoryFinance: "Financial / loan issue",
    subject: "Subject",
    subjectPlaceholder: "e.g. PACS not disbursing crop loan",
    description: "Description",
    descriptionPlaceholder: "Explain what happened, when, and which office was involved.",
    submitGrievance: "Submit grievance",
    emptyTitle: "No grievances filed yet",
    emptySubtitle: "You can also file one by chatting with the assistant.",
    filed: "Filed",
    statusOpen: "Open",
    statusInReview: "In review",
    statusEscalated: "Escalated",
    statusResolved: "Resolved",
    statusClosed: "Closed",
  },

  settings: {
    title: "Settings",
    languageTitle: "Language",
    languageSubtitle: "Choose how the assistant responds. English is the default for every account.",
    englishOnly: "English only",
    englishOnlyDesc: "Default. The assistant always replies in English.",
    multilingual: "Multilingual",
    multilingualDesc: "Pick a default language; switch anytime from the chat header.",
    defaultLanguage: "Default language",
    voiceNote:
      "Voice input follows the same language. If a spoken language isn't supported by the voice engine yet, the assistant falls back to your device's built-in speech recognition automatically.",
    modelTitle: "AI Model",
    modelSubtitle:
      "Each model has its own separate daily free-tier limit. If replies stop working, the assistant already tries other stable models automatically — but you can also switch here to pick a different one right away.",
    modelStable: "Stable",
    modelLatest: "Auto-updating — points to whatever is newest; can change without notice",
    modelPreview: "Preview — early-access, may be less reliable",
    modelDefault: "default",
    profileTitle: "Profile",
    profileSubtitle: "Helps the assistant give locally relevant guidance.",
    fullName: "Full name",
    phone: "Phone",
    state: "State",
    district: "District",
    pacsName: "PACS name",
    aboutTitle: "About Sahakar Sathi",
    aboutSubtitle: "Built for Smart India Hackathon 2026 — Problem Statement 26088, Ministry of Cooperation / NCCT.",
    team: "Team",
  },

  // Descriptive scheme NAMES only, keyed by the schemes.code DB column
  // (PMFBY, SAHAKAR-M, PACS-CSC, NCDC-YUVA, KCC — see supabase/migrations/
  // 0003_seed.sql). The short code itself is never translated (official
  // abbreviations stay identical across languages, same as "KCC" in a
  // Tamil government document); only the fuller name shown under it in
  // the dashboard sidebar is. summary/benefits/eligibility text is NOT
  // duplicated here — that's surfaced through the AI/RAG pipeline, which
  // already replies in the selected language on its own.
  schemes: {
    "PMFBY": "Pradhan Mantri Fasal Bima Yojana",
    "SAHAKAR-M": "Sahakar Mitra Internship",
    "PACS-CSC": "PACS as Common Service Centres",
    "NCDC-YUVA": "NCDC Yuva Sahakar",
    "KCC": "Kisan Credit Card",
  },

  // Citation chip titles shown under an assistant reply, keyed by the
  // ENGLISH title text itself (kb_documents.title, every row currently
  // lang='en' — confirmed via a live query against the 5 rows that exist
  // today). Keyed by title text rather than kb_documents.id because the
  // `chat` function's citations array (supabase/functions/chat/index.ts,
  // match_kb_chunks RPC) never returns the document id at all, only
  // title/source_url/similarity -- changing that would need a DB
  // function + Edge Function change, which isn't needed here since the
  // 5 existing titles are already unique. Same reasoning as `schemes`
  // above: a small, fixed, hand-translated set. If a future kb_documents
  // title isn't a key here, the dashboard falls back to showing that
  // English title as-is rather than a raw lookup-path string.
  citations: {
    "Multi-State Cooperative Societies Act, 2002 — Member Rights & Governance": "Multi-State Cooperative Societies Act, 2002 — Member Rights & Governance",
    "Model By-Laws for Primary Agricultural Credit Societies (PACS)": "Model By-Laws for Primary Agricultural Credit Societies (PACS)",
    "PMFBY Operational Guidelines — Claims, Premium & Timelines": "PMFBY Operational Guidelines — Claims, Premium & Timelines",
    "Kisan Credit Card — Eligibility, Limits & Financial Literacy": "Kisan Credit Card — Eligibility, Limits & Financial Literacy",
    "Cooperative Grievance Redressal — Authorities & Escalation Path": "Cooperative Grievance Redressal — Authorities & Escalation Path",
  },
} as const;

export default en;

// Widen every leaf string literal to `string` so translation files (which have
// the same shape but different text) satisfy this type structurally.
type Widen<T> = T extends string ? string : { [K in keyof T]: Widen<T[K]> };
export type TranslationDict = Widen<typeof en>;
