#!/usr/bin/env node
/**
 * Writes .env.local from the Supabase Management API.
 * Usage: SB_TOKEN=sbp_xxx node scripts/fetch-env.mjs
 * Secrets are written to disk only — never printed to stdout.
 */
import fs from "node:fs";

const TOKEN = process.env.SB_TOKEN;
const REF = process.env.SB_REF || "njpxixfcctodjejtgmwj";
if (!TOKEN) { console.error("Missing SB_TOKEN env var."); process.exit(1); }

const res = await fetch(`https://api.supabase.com/v1/projects/${REF}/api-keys?reveal=true`, {
  headers: { Authorization: `Bearer ${TOKEN}` },
});
if (!res.ok) { console.error("Failed to fetch keys:", res.status); process.exit(1); }

const keys = await res.json();
const pick = (n, t) => keys.find(k => k.name === n && k.type === t)?.api_key;
const anon = pick("anon", "legacy") ?? keys.find(k => k.type === "publishable")?.api_key;
const service = pick("service_role", "legacy") ?? keys.find(k => k.type === "secret")?.api_key;
if (!anon) { console.error("No anon/publishable key found."); process.exit(1); }

const lines = [
  "# Auto-generated by scripts/fetch-env.mjs — DO NOT COMMIT",
  `NEXT_PUBLIC_SUPABASE_URL=https://${REF}.supabase.co`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}`,
  "",
  "# Server-side only. Used by Edge Function deploys, never shipped to the browser.",
  `SUPABASE_SERVICE_ROLE_KEY=${service ?? ""}`,
  "",
  "# --- Fill these in yourself (see README) ---",
  "GEMINI_API_KEY=",
  "SARVAM_API_KEY=",
  "",
].join("\n");

fs.writeFileSync(".env.local", lines);
console.log("Wrote .env.local");
console.log(`  NEXT_PUBLIC_SUPABASE_URL   = https://${REF}.supabase.co`);
console.log(`  NEXT_PUBLIC_SUPABASE_ANON_KEY = ${anon.slice(0, 8)}…${anon.slice(-4)} (${anon.length} chars)`);
console.log(`  SUPABASE_SERVICE_ROLE_KEY     = ${service ? service.slice(0,8) + "…(set)" : "(not found)"}`);
